# Generated by Django 4.1.6 on 2023-02-11 12:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='chat_news.tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='picture',
            name='url',
        ),
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(null=True, upload_to='static/static/'),
        ),
        migrations.AddField(
            model_name='picture',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='chat_news.tag'),
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AddField(
            model_name='picture',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='chat_news.post'),
        ),
    ]
