# Generated by Django 4.1.6 on 2023-02-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_news', '0002_post_remove_picture_url_picture_image_picture_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(null=True, upload_to='static/media/'),
        ),
    ]
